{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "initial_id",
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "#!pip install kafka-python\n",
    "#!pip install pymongo"
   ]
  },
  {
   "metadata": {},
   "cell_type": "code",
   "source": [
    "from kafka import KafkaConsumer\n",
    "import pymongo\n",
    "import json\n",
    "\n",
    "def is_valid_data(data):\n",
    "    \"\"\" Überprüft, ob alle Einträge in der Daten nicht None sind. \"\"\"\n",
    "    for key, value in data.items():\n",
    "        if value is None:\n",
    "            print(f\"Ungültiger Eintrag gefunden: {key} ist None\")\n",
    "            return False\n",
    "    return True\n",
    "\n",
    "mongo_conn_uri = "######",
    "client = pymongo.MongoClient(mongo_conn_uri)\n",
    "db = client.swtp_a\n",
    "collection = db.test_collection\n",
    "\n",
    "decode = lambda x: json.loads(x.decode('utf-8'))\n",
    "consumer = KafkaConsumer(bootstrap_servers=\"###", auto_offset_reset = \"latest\") #value_deserializer=decode)\n",
    "consumer.subscribe(topics = [\"###"])\n",
    "#counter\n",
    "for message in consumer:\n",
    "    try:\n",
    "        data = json.loads(message.value)\n",
    "        if is_valid_data(data):\n",
    "            result = collection.insert_one(data)\n",
    "            print(f\"Daten eingefügt: {data}, ID: {result.inserted_id}\")\n",
    "        else:\n",
    "            print(\"Daten nicht eingefügt, da ein oder mehrere Einträge None sind.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Fehler beim Einfügen der Daten: {e}\")\n"
   ],
   "id": "5dfbd191a9faa26a",
   "outputs": [],
   "execution_count": null
  },
  {
   "cell_type": "markdown",
   "source": [
    "# Normal(Nicht Anomalie) Daten einfügen"
   ],
   "metadata": {
    "collapsed": false
   },
   "id": "492d36d7ed139e91"
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "# Normal(Nicht Anomalie) Daten einfügen\n",
    "from kafka import KafkaConsumer\n",
    "import pymongo\n",
    "import json\n",
    "\n",
    "def is_valid_data(data):\n",
    "    \"\"\" Überprüft, ob alle Einträge in den Daten nicht None sind. \"\"\"\n",
    "    for key, value in data.items():\n",
    "        if value is None:\n",
    "            print(f\"Ungültiger Eintrag gefunden: {key} ist None\")\n",
    "            return False\n",
    "    return True\n",
    "def verify_gx_sum(gx_kafka_sum, first_counter, last_counter, collection):\n",
    "    \"\"\" Überprüft, ob die Summe der 'gx'-Datenpunkte in den letzten 100 Datensätzen in Kafka und in der DB übereinstimmen. \"\"\"\n",
    "    try:\n",
    "        gx_db_sum = sum(\n",
    "            doc['gx'] for doc in collection.find({\"counter\": {\"$gte\": first_counter, \"$lte\": last_counter}})\n",
    "        )\n",
    "        if gx_db_sum == gx_kafka_sum:\n",
    "            print(f\"Die Summe der gx-Werte für die Datensätze {first_counter} bis {last_counter} stimmt überein: {gx_db_sum}\")\n",
    "        else:\n",
    "            print(f\"Die Summe der gx-Werte für die Datensätze {first_counter} bis {last_counter} stimmt NICHT überein! (Kafka: {gx_kafka_sum}, DB: {gx_db_sum})\")\n",
    "    except Exception as e:\n",
    "        print(f\"Fehler beim Überprüfen der gx-Werte: {e}\")\n",
    "\n",
    "def verify_number_of_data(first_counter, last_counter, collection):\n",
    "    \"\"\" Überprüft, ob die Anzahl der Datensätze in den letzten 100 in Kafka und in der DB übereinstimmen. \"\"\"\n",
    "    try:\n",
    "        differnz = last_counter - first_counter + 1\n",
    "        counter_db_count = collection.count_documents({\"counter\": {\"$gte\": first_counter, \"$lte\": last_counter}})\n",
    "        if differnz == counter_db_count:\n",
    "            print(\"Die Daten sind vollständig, keine Daten sind verloren gegangen.\")\n",
    "        else:\n",
    "            print(f\"Die Anzahl der verlorenen Daten: {differnz - counter_db_count}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Fehler beim Überprüfen der Anzahl der Daten: {e}\")\n",
    "        \n",
    "mongo_conn_uri = \"##"\n",
    "client = pymongo.MongoClient(mongo_conn_uri)\n",
    "db = client.swtp_a\n",
    "collection = db.swtp_a_collection\n",
    "\n",
    "decode = lambda x: json.loads(x.decode('utf-8'))\n",
    "consumer = KafkaConsumer(bootstrap_servers=\"####", auto_offset_reset = \"latest\") #value_deserializer=decode)\n",
    "consumer.subscribe(topics = [\"####"])\n",
    "\n",
    "gx_kafka_sum = 0\n",
    "message_count = 0\n",
    "first_counter = None\n",
    "\n",
    "\n",
    "for message in consumer:\n",
    "    try:\n",
    "        data = json.loads(message.value)\n",
    "        data['label'] = 1\n",
    "        if is_valid_data(data):\n",
    "            result = collection.insert_one(data)\n",
    "            print(f\"Daten eingefügt: {data}, ID: {result.inserted_id}\")\n",
    "            gx_kafka_sum += data['gx']\n",
    "            if first_counter is None:\n",
    "                first_counter = data['counter']\n",
    "                print(f\"Erster Counter: {first_counter}\")\n",
    "            last_counter = data['counter']\n",
    "            print(f\"Letzter Counter: {last_counter}\")\n",
    "            message_count += 1\n",
    "            \n",
    "            if message_count == 100:\n",
    "                verify_gx_sum(gx_kafka_sum, first_counter, last_counter, collection)\n",
    "                verify_number_of_data( first_counter, last_counter, collection)\n",
    "                message_count = 0\n",
    "                gx_kafka_sum = 0\n",
    "                first_counter = None\n",
    "        else:\n",
    "            print(\"Daten nicht eingefügt, da ein oder mehrere Einträge None sind.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Fehler beim Einfügen der Daten: {e}\")"
   ],
   "metadata": {
    "collapsed": false
   },
   "id": "3fbf60919dd5e80d"
  },
  {
   "cell_type": "markdown",
   "source": [
    "# Anomalie Daten einfügen "
   ],
   "metadata": {
    "collapsed": false
   },
   "id": "8211f2e54872c5eb"
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "from kafka import KafkaConsumer\n",
    "import pymongo\n",
    "import json\n",
    "\n",
    "def is_valid_data(data):\n",
    "    \"\"\" Überprüft, ob alle Einträge in den Daten nicht None sind. \"\"\"\n",
    "    for key, value in data.items():\n",
    "        if value is None:\n",
    "            print(f\"Ungültiger Eintrag gefunden: {key} ist None\")\n",
    "            return False\n",
    "    return True\n",
    "def verify_gx_sum(gx_kafka_sum, first_counter, last_counter, collection):\n",
    "    \"\"\" Überprüft, ob die Summe der 'gx'-Datenpunkte in den letzten 100 Datensätzen in Kafka und in der DB übereinstimmen. \"\"\"\n",
    "    try:\n",
    "        gx_db_sum = sum(\n",
    "            doc['gx'] for doc in collection.find({\"counter\": {\"$gte\": first_counter, \"$lte\": last_counter}})\n",
    "        )\n",
    "        if gx_db_sum == gx_kafka_sum:\n",
    "            print(f\"Die Summe der gx-Werte für die Datensätze {first_counter} bis {last_counter} stimmt überein: {gx_db_sum}\")\n",
    "        else:\n",
    "            print(f\"Die Summe der gx-Werte für die Datensätze {first_counter} bis {last_counter} stimmt NICHT überein! (Kafka: {gx_kafka_sum}, DB: {gx_db_sum})\")\n",
    "    except Exception as e:\n",
    "        print(f\"Fehler beim Überprüfen der gx-Werte: {e}\")\n",
    "\n",
    "def verify_number_of_data(first_counter, last_counter, collection):\n",
    "    \"\"\" Überprüft, ob die Anzahl der Datensätze in den letzten 100 in Kafka und in der DB übereinstimmen. \"\"\"\n",
    "    try:\n",
    "        differnz = last_counter - first_counter + 1\n",
    "        counter_db_count = collection.count_documents({\"counter\": {\"$gte\": first_counter, \"$lte\": last_counter}})\n",
    "        if differnz == counter_db_count:\n",
    "            print(\"Die Daten sind vollständig, keine Daten sind verloren gegangen.\")\n",
    "        else:\n",
    "            print(f\"Die Anzahl der verlorenen Daten: {differnz - counter_db_count}\")\n",
    "    except Exception as e:\n",
    "        print(f\"Fehler beim Überprüfen der Anzahl der Daten: {e}\")\n",
    "        \n",
    "mongo_conn_uri = \"####"\n",
    "client = pymongo.MongoClient(mongo_conn_uri)\n",
    "db = client.swtp_a\n",
    "collection = db.swtp_a_anomali\n",
    "\n",
    "decode = lambda x: json.loads(x.decode('utf-8'))\n",
    "consumer = KafkaConsumer(bootstrap_servers=\"####", auto_offset_reset = \"latest\") #value_deserializer=decode)\n",
    "consumer.subscribe(topics = [\"swtp_team_a\"])\n",
    "\n",
    "gx_kafka_sum = 0\n",
    "message_count = 0\n",
    "first_counter = None\n",
    "\n",
    "\n",
    "for message in consumer:\n",
    "    try:\n",
    "        data = json.loads(message.value)\n",
    "        data['label'] = 0\n",
    "        if is_valid_data(data):\n",
    "            result = collection.insert_one(data)\n",
    "            print(f\"Daten eingefügt: {data}, ID: {result.inserted_id}\")\n",
    "            gx_kafka_sum += data['gx']\n",
    "            if first_counter is None:\n",
    "                first_counter = data['counter']\n",
    "                print(f\"Erster Counter: {first_counter}\")\n",
    "            last_counter = data['counter']\n",
    "            print(f\"Letzter Counter: {last_counter}\")\n",
    "            message_count += 1\n",
    "            \n",
    "            if message_count == 100:\n",
    "                verify_gx_sum(gx_kafka_sum, first_counter, last_counter, collection)\n",
    "                verify_number_of_data( first_counter, last_counter, collection)\n",
    "                message_count = 0\n",
    "                gx_kafka_sum = 0\n",
    "                first_counter = None\n",
    "        else:\n",
    "            print(\"Daten nicht eingefügt, da ein oder mehrere Einträge None sind.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Fehler beim Einfügen der Daten: {e}\")"
   ],
   "metadata": {
    "collapsed": false
   },
   "id": "d838d4785bcd3958"
  },
  {
   "metadata": {},
   "cell_type": "code",
   "outputs": [],
   "execution_count": null,
   "source": [],
   "id": "6ed10c60293af432"
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
